### ISSUE TITLE
ImportError: No module named _multiprocess

### ISSUE THREAD

**Issue by mdk73** [uqfoundation/multiprocess#10]
I installed multiprocess via pip (python 2.7 on Win10). The installation seemed to be successful.

But when I use the example code
```Python
    from multiprocess import Process, Queue

    def f(q):
        q.put('hello world')

    if __name__ == '__main__':
        q = Queue()
        p = Process(target=f, args=[q])
        p.start()
        print q.get()
        p.join()
```
I get an error message:
*Traceback (most recent call last):
  File "C:\Users\mdk\Desktop\test_process.py", line 1, in <module>
    from multiprocess import Process, Queue
  File "C:\Python27\lib\site-packages\multiprocess\__init__.py", line 84, in <module>
    import _multiprocess as _multiprocessing
ImportError: No module named _multiprocess*

**Comment by mmckerns** [comment]
The install was not complete.  You need a C++ compiler, like the `Microsoft Visual C++ Compiler for Python 2.7`.  `_multiprocess` requires a C++ compiler, and if one is not found… some of `multiprocess` (the python part of the module) may still work.  Hence, a warning is printed during the install, but an error is not thrown.   **Maybe** an error should be thrown, or a wheel should be included...

**Comment by mmckerns** [comment]
See #8

**Comment by mdk73** [comment]
I installed the tools mentioned in #8.

The log for pip looks like this

*PS C:\Users\mdk\Downloads\multiprocess-0.70.3> pip install multiprocess
Collecting multiprocess
Collecting dill>=0.2.3 (from multiprocess)
Collecting pyreadline>=1.7.1 (from dill>=0.2.3->multiprocess)
Installing collected packages: pyreadline, dill, multiprocess
Successfully installed dill-0.2.4 multiprocess-0.70.3 pyreadline-2.1
PS C:\Users\mdk\Downloads\multiprocess-0.70.3>*

but I still get the same error message.

So I tried with setup.py
I could not see any errors during the build or install, but I get still the same error message.
What am I missing? 
[build.txt](https://github.com/uqfoundation/multiprocess/files/59782/build.txt)
[install.txt](https://github.com/uqfoundation/multiprocess/files/59783/install.txt)

**Comment by mmckerns** [comment]
FYI, workaround added in: 02c1480e3e0a8d6740a2234f1f757d8d90dc7705
