### ISSUE TITLE
Corrupted call stack with Python 3.10

### ISSUE THREAD

**Issue by snordhausen** [uqfoundation/multiprocess#109]
When calling Python's builtin function `inspect.stack()` from a worker in a `multiprocess.Pool`, sometimes the stack inspections fails with a `TypeError`. The code below does that 50 times, which triggers the issue multiple times on my system:
```
code = """
import inspect
from multiprocess.pool import Pool

def load(x):
    inspect.stack()

try:
    pool = Pool(1)
    pool.map(load, range(1))
finally:
    pool.terminate()
    pool.join()
"""
with open("inspector.py", "w") as inspector:
    inspector.write(code)

import os
for i in range(50):
    os.system("python3 inspector.py")
```
This happens for
* Python 3.10, but not Python 3.9
* `multiprocess.Pool`, but not Python's builtin `multiprocessing.Pool`
* versions 0.70.13 and 0.70.12.2 of `multiprocess`

The traceback says:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/site-packages/multiprocess/pool.py", line 48, in mapstar
    return list(map(*args))
  File "//inspector.py", line -40, in load
  File "/usr/local/lib/python3.10/inspect.py", line 1678, in stack
    return getouterframes(sys._getframe(1), context)
  File "/usr/local/lib/python3.10/inspect.py", line 1655, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File "/usr/local/lib/python3.10/inspect.py", line 1627, in getframeinfo
    start = lineno - 1 - context//2
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```
Note the line `File "//inspector.py", line -40, in load` with the incorrect path `//` and the negative line number. The line number actually differs between the runs.

Test setup:
* Official Python docker container `python:3.10.4-bullseye`
* `pip list` says
```
# pip list
Package      Version
------------ -------
dill         0.3.5.1
multiprocess 0.70.13
pip          22.0.4
setuptools   58.1.0
wheel        0.37.1
```

The issue was originally discovered because `pandas` 1.4.2 [actually calls](https://github.com/pandas-dev/pandas/blob/v1.4.2/pandas/util/_exceptions.py#L32) `inspect.stack()` when it produces warnings.

**Comment by snordhausen** [comment]
Actually, an even easier way to just see the corrupted call stack is
```
from multiprocess.pool import Pool

def load(x):
    raise Exception

try:
    pool = Pool(1)
    pool.map(load, range(1))
finally:
    pool.terminate()
    pool.join()
```
which produces tracebacks like
```
multiprocess.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/site-packages/multiprocess/pool.py", line 48, in mapstar
    return list(map(*args))
  File "//foo.py", line -1, in load
Exception
```
Again with an incorrect path and a negative line numbers (or line numbers that are far too high).

**Comment by snordhausen** [comment]
The incorrect path also happens with Python 3.8 and 3.9. But for these Python versions, at least the line number is correct which might explain why `inspect.stack()` does not fail with `TypeError`. So while it is a small inconvenience in the older Python versions, in Python 3.10 it actually leads to random crashes.

**Comment by snordhausen** [comment]
The incorrect line numbers might be related to a [change in the C API in Python 3.10](https://docs.python.org/3/whatsnew/3.10.html?highlight=mutablemapping#changes-in-the-c-api):
> For FrameObject objects, the f_lasti member now represents a wordcode offset instead of a simple offset....

**Comment by mmckerns** [comment]
Hi @snordhausen: thanks for the detailed report.  I think it might be due to an issue in `dill` with regard to the change from `lnotab` to `linetable` from PEP626.  See: https://github.com/uqfoundation/dill/pull/495.  If you use `dill` master, it should work.
```
multiprocess.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/mmckerns/lib/python3.10/site-packages/multiprocess-0.70.14.dev0-py3.10.egg/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/mmckerns/lib/python3.10/site-packages/multiprocess-0.70.14.dev0-py3.10.egg/multiprocess/pool.py", line 48, in mapstar
    return list(map(*args))
  File "<stdin>", line 2, in load
Exception
"""
```
Please reopen the issue if that doesn't resolve it for you.

**Comment by snordhausen** [comment]
Yes, the negative line numbers are fixed when installing the `master` branch of `dill`. Thanks for the hint!
