### ISSUE TITLE
Running across [Errno 9] Bad file descriptor when using synchronized Value

### ISSUE THREAD

**Issue by petereon** [uqfoundation/multiprocess#115]
Hello, I am running across an `OSError: [Errno 9] Bad file descriptor` when attempting to access a shared `Value` in a `SpawnProcess` on `multiprocess==0.70.13`. Is this a bug or am I doing something very wrong and this is an expected behavior?

Here is the minimal example:
```python
from multiprocess.sharedctypes import Value
from multiprocess import Lock
from multiprocess.context import SpawnProcess


def increment(val: Value, lock):
    with lock:
        val.value += 1


if __name__ == "__main__":
    lock = Lock()
    val = Value('i', 0)
    process = SpawnProcess(target=increment, args=(val, lock))
    process.start()
```

and here is a full traceback:
```
Traceback (most recent call last):
  File "/Users/macbookpro/Library/Caches/pypoetry/virtualenvs/woflo-KXSkunlW-py3.10/lib/python3.10/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/macbookpro/Library/Caches/pypoetry/virtualenvs/woflo-KXSkunlW-py3.10/lib/python3.10/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/macbookpro/Projects/woflo/run.py", line 9, in increment
    val.value += 1
  File "/Users/macbookpro/Library/Caches/pypoetry/virtualenvs/woflo-KXSkunlW-py3.10/lib/python3.10/site-packages/multiprocess/synchronize.py", line 101, in __enter__
    return self._semlock.__enter__()
OSError: [Errno 9] Bad file descriptor
```

Platform:

- OS: macOS 12.6
- Python: 3.10.6

Thanks in advance!

**Comment by petereon** [comment]
Update: I have tested against a Fedora 36 within Docker container and the error no longer appears, seems to be platform dependent.

**Comment by mmckerns** [comment]
What is your version of `dill`?

**Comment by petereon** [comment]
My version of `dill` is 0.3.5.1

**Comment by mmckerns** [comment]
Hmm, I've not tried to use a context like this before with a `Value`.  First thing to note is that if I substitute `multiprocessing` for `multiprocess`, I get the same result (for python 3.7-3.11 on a mac).

**Comment by petereon** [comment]
That is a good point, didn't occur to me to check. I also observed this with few other things on `mutliprocessing` on Mac. I've came to understand `multiprocessing` relies on some kernel level stuff that's outside of Unix spec and is only implemented on Linux. I will be closing this as I seem to be barking up the wrong tree. Thanks for help!
