### ISSUE TITLE
Error in python 3.11.0 fork_exec() takes exactly 23 arguments (21 given)

### ISSUE THREAD

**Issue by xzy3** [uqfoundation/multiprocess#122]
I traced the problem back to https://github.com/uqfoundation/multiprocess/blob/0664c9033ba5eff5f6137eddf910175adaa86a59/py3.11/multiprocess/util.py#L453 

It seems to stem from this change in CPython a few months ago https://github.com/python/cpython/commit/f6dd14c65336cda4e2ebccbc6408dfe3b0a68a34 and the addition of `pgid_to_set` to the parameter list.

**Comment by mmckerns** [comment]
@xzy3: can you be a bit more specific and/or detailed? The line you are referencing is unchanged from Python 3.11.0, so if there are missing arguments... then it's a bug in Python 3.11.0.  I'll be happy to apply a patch in `multiprocess`. If you don't mind, could you post a small test code that triggers the behavior (i.e. error) you are seeing. The traceback would also be good, or at the very least the tail end of it. Thanks.

**Comment by xzy3** [comment]
The traceback propagates from that line. And the title of the bug, past "Python 3.11.0" is the exact error message. I'll try and dig out a specific example, but i'm just using map from a pool. The code has been working for several years now and breaks on two different source installs of Python 3.11.0.

**Comment by mmckerns** [comment]
I'm not seeing an error with `Pool().map`:
```
Python 3.11.0 (main, Oct 25 2022, 16:30:48) [Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import multiprocess as mp
>>> p = mp.Pool()
>>> p.map(lambda x:x, range(4))
[0, 1, 2, 3]
>>> p.close()
>>> mp.__version__
'0.70.15.dev0'
>>> import dill
>>> dill.__version__
'0.3.7.dev0'
```
and all the tests pass on macOS (my laptop) and linux (travis CI).

What OS are you using? What's your version of `multiprocess` and `dill`?  Again, I'd appreciate some code that triggers the error.

**Comment by xzy3** [comment]
CentOS Stream 8

Here's your code. It was 1 am and I wasn't at work, hold your horses.
```python
import multiprocess as mp

context = mp.get_context()
with context.Pool() as pool:
    pass

context = mp.get_context('spawn')
with context.Pool() as pool:
     pass
```

The first one works the second one throws the error.

```
>>> multiprocess.__version__
'0.70.14'
>>> dill.__version__
'0.3.6'
>>>
```
```
(python11-test) xzy3@scbs-mue-prod-01> python multiprocess-test.py
Traceback (most recent call last):
  File "/scicomp/home-pure/xzy3/multiprocess-test.py", line 8, in <module>
    with context.Pool() as pool:
         ^^^^^^^^^^^^^^
  File "/scicomp/home-pure/xzy3/.local/virtualenvs/python11-test/lib/python3.11/site-packages/multiprocess/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scicomp/home-pure/xzy3/.local/virtualenvs/python11-test/lib/python3.11/site-packages/multiprocess/pool.py", line 191, in __init__
    self._setup_queues()
  File "/scicomp/home-pure/xzy3/.local/virtualenvs/python11-test/lib/python3.11/site-packages/multiprocess/pool.py", line 346, in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/scicomp/home-pure/xzy3/.local/virtualenvs/python11-test/lib/python3.11/site-packages/multiprocess/context.py", line 113, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scicomp/home-pure/xzy3/.local/virtualenvs/python11-test/lib/python3.11/site-packages/multiprocess/queues.py", line 344, in __init__
    self._rlock = ctx.Lock()
                  ^^^^^^^^^^
  File "/scicomp/home-pure/xzy3/.local/virtualenvs/python11-test/lib/python3.11/site-packages/multiprocess/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scicomp/home-pure/xzy3/.local/virtualenvs/python11-test/lib/python3.11/site-packages/multiprocess/synchronize.py", line 168, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/scicomp/home-pure/xzy3/.local/virtualenvs/python11-test/lib/python3.11/site-packages/multiprocess/synchronize.py", line 86, in __init__
    register(self._semlock.name, "semaphore")
  File "/scicomp/home-pure/xzy3/.local/virtualenvs/python11-test/lib/python3.11/site-packages/multiprocess/resource_tracker.py", line 158, in register
    self._send('REGISTER', name, rtype)
  File "/scicomp/home-pure/xzy3/.local/virtualenvs/python11-test/lib/python3.11/site-packages/multiprocess/resource_tracker.py", line 165, in _send
    self.ensure_running()
  File "/scicomp/home-pure/xzy3/.local/virtualenvs/python11-test/lib/python3.11/site-packages/multiprocess/resource_tracker.py", line 132, in ensure_running
    pid = util.spawnv_passfds(exe, args, fds_to_pass)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scicomp/home-pure/xzy3/.local/virtualenvs/python11-test/lib/python3.11/site-packages/multiprocess/util.py", line 452, in spawnv_passfds
    return _posixsubprocess.fork_exec(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: fork_exec() takes exactly 23 arguments (21 given)
```

**Comment by mmckerns** [comment]
Ok, thanks. I appreciate the quick response.

Interesting...
```
>>> import multiprocess as mp
>>> 
>>> context = mp.get_context()
>>> with context.Pool() as pool:
...     pass
... 
>>> context = mp.get_context('spawn')
>>> with context.Pool() as pool:
...      pass
... 
```
Same result when run from a file.

**Comment by mmckerns** [comment]
Reverting to the release version makes no difference.
```
>>> import multiprocess as mp
>>> mp.__version__
'0.70.14'
>>> import multiprocess as mp
>>> 
>>> context = mp.get_context()
>>> with context.Pool() as pool:
...     pass
... 
>>> context = mp.get_context('spawn')
>>> with context.Pool() as pool:
...      pass
... 
>>>
```

**Comment by mmckerns** [comment]
For me, the traceback yields matching line numbers to my copy of the code... until the last file -- util.py.  On line 453, I have:
```
        return _posixsubprocess.fork_exec(
            args, [path], True, passfds, None, None,
            -1, -1, -1, -1, -1, -1, errpipe_read, errpipe_write,
            False, False, -1, None, None, None, -1, None,
            subprocess._USE_VFORK)
```
which has 23 arguments.

**Comment by Psykopear** [comment]
Hi @mmckerns, friendly ping. Is there something blocking the `0.70.15` release?
I'd like this PR to be released so I can add support for python 3.11 to a library I'm working on that depends on `multiprocess`

**Comment by mmckerns** [comment]
No blockers. It's due, for formal 3.11 support. I had surgery a few days ago, so I'm taking it a bit easy... but I can probably get a release scheduled if not get one cut soon.

**Comment by Psykopear** [comment]
Thanks for the answer.

Needless to say, but take all the time you need to recover, I didn't mean to put pressure on you, I'll wait :)

**Comment by sybrenjansen** [comment]
Hi @mmckerns, I hope you're recovered well!

I'm in the same situation as @Psykopear , I too need it so I can add support for 3.11.

Do you have any insights on when the next release will happen? Thnx!

**Comment by mmckerns** [comment]
@sybrenjansen: I'm scheduled to release it this week, but it will probably slip a week or so.

**Comment by tachikoma-li** [comment]
Hi @mmckerns, hope you have a good recovery!
Just wondering when the next release will be available? Thanks!

**Comment by mmckerns** [comment]
There's a weird 3.12a7 / b1 bug that I seem to be experiencing, which may delay things a day or so if I try to figure that out before releasing.
