### ISSUE TITLE
 Celery/Scrapy/Multiprocessing ModuleNotFoundError

### ISSUE THREAD

**Issue by thisiseddy-ab** [uqfoundation/multiprocess#126]
Im Trying to use Celery with Scrapy and it use multiprocessing like in this example
[https://codeburst.io/running-scrapy-in-celery-tasks-d81e159921ea](https://codeburst.io/running-scrapy-in-celery-tasks-d81e159921ea)

### Module Folder Struture
```
- aggregators_parser
    . booklender_aggregator.py
. celery_app.py
```

### booklender_aggregator.py
```py
def get_book_info_crawler(url):
        crawler = Crawler(Booklender_Aggregator_Spider,settings = spalsh_settings)

        # Scrapy uses Twistet behind the scene
        # This makes sure Twistet Reactor is properly shutdown
        crawler.signals.connect(reactor.stop,signal=signals.spider_closed)

        ## You Can Pass arguments
        extra_spider_args = {"url ": url, "parser":"self.get_book_info"}
        
        ### Start Crawling
        crawler.crawl(**extra_spider_args)

        reactor.run()

def get_book_info(value,v_type = "isbn"):
        if v_type == "isbn" or v_type == "link":
            if v_type == "isbn":   
                url = f"https://www.booklender.com/search/{value}"
            if v_type == "link":
                url = value

            ### Here Runs the Process
            p = Process(target=get_book_info_crawler, args=(url))
            p.start()
            p.join()

```

### celery_app.py
```py
from aggregators_parser.booklender_aggregator import get_book_info as booklender_get_book_info

@celery.task(name="task.tryspider")
def add_newspapers():
    booklender_get_book_info(value = "9781501161933",v_type = "isbn")
    
```

When in run the task i get this error:
```
 File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
ModuleNotFoundError: No module named 'aggregators_parser
```

**Comment by mmckerns** [comment]
> Im Trying to use Celery with Scrapy and it use multiprocessing like in this example

Your link doesn't work... and your example seems incomplete. Where is `Process` imported from? Is it from `multiprocessing` or `multiprocess`. This is the latter.  The former is part of the python STL.

**Comment by thisiseddy-ab** [comment]
> 

im importing from multiprocessing sorry i thought this is the same

**Comment by mmckerns** [comment]
Thanks for fixing the link.  It's still a bit difficult to follow what exactly you are doing, and what you are experiencing. As you done have a self-contained minimal working example, I can try to help through Q&A.  It seems to me that `aggregators_parser` is a folder located in the directory that you are running the script in, and not an installed module. Generally, you can pickle contents from a script you are running, but there's a good bit of difficulty pickling from a module that isn't *installed*.  My first suggestion would be to either install `aggregators_parser` or merge it with the script you are running as `__main__`.

**Comment by thisiseddy-ab** [comment]
> 

thanks i found out i can use Splash Browser without scrapy i don't need for this so im good
