### ISSUE TITLE
pip install pathos doesn't work

### ISSUE THREAD

**Issue by andyfaff** [uqfoundation/multiprocess#13]
I tried to install pathos using miniconda + py3.4.  I get the following errors:

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/d0/kxzh7pwd4c10bzx7wffq8s740000gn/T/pip-build-dw9bfq7k/pathos/setup.py", line 66
        exec setup_code
                      ^
    SyntaxError: Missing parentheses in call to 'exec'

From looking around it seems that pathos can only be used on Py2, is that correct? If so, then is there an alternative for Py3?

**Comment by mmckerns** [comment]
`pathos` is 90% python3 compatible.  but that doesn't help.  There is some `ssh` connection stuff that I don't know how to convert yet… however, it's not a critical part of the package.   So, the plan is to cut a new release that doesn't support the `ssh` features of `pathos` for python3… and fix that when I get time.  I had planned to release `pathos` in January, however, I just released all the support packages (like `multiprocess`) this weekend… so I am a little behind.  I don't expect it too much longer a delay however.

**Comment by mmckerns** [comment]
This is actually a `pathos` ticket, not a `multiprocess` ticket… so I'm closing it here.  See [#43](https://github.com/uqfoundation/pathos/issues/43) in the `pathos` tickets… and links therein for how to build `pathos` with `pip`.
