### ISSUE TITLE
AssertionError: group argument must be None for now

### ISSUE THREAD

**Issue by menichel** [uqfoundation/multiprocess#132]
Hi all,

I am using Python 3.10.6 and I installed the multiprocess package using "pip install multiprocess" inside a virtual environment. As OS, I am using Ubuntu 22.04 LTS.

I try to run this code:
![image](https://user-images.githubusercontent.com/122894387/218996622-255f8f67-2cfe-4015-bca8-eb9cc505075e.png)

and get this error:
![image](https://user-images.githubusercontent.com/122894387/218996898-3ff286c8-8c6f-4faa-b2a5-ac9037167e56.png)

Thank you in advance for you help!

menichel

**Comment by mmckerns** [comment]
Apparently the python developers thought it a good idea to make the first arg of `Process` something that shouldn't be set to anything but the default.  So, the solution is either make the first positional argument `None`, or pass a dict of arguments.
