### ISSUE TITLE
Same output for all processes?

### ISSUE THREAD

**Issue by Hana-Ali** [uqfoundation/multiprocess#138]
Hello,

I'm trying to run multiprocessing on a loop, such that I repeat a certain operation 5 times. When I do this serially, I get different values across all 5 replications (they're not connected to each other, but each is a stochastic process so this is expected). When I do this in parallel, I get the same result for all 5. Is this expected behaviour?

Thank you,
Hana

**Comment by mmckerns** [comment]
it deepens. if you are passing a random number generator to each of the different processes, then no. if you are using a random number generator to seed a calculation, and all the processes are getting the same seed, then yes.  Does that help?  If this doesn't answer your question, then please provide a code example that demonstrates what you are seeing.

**Comment by Hana-Ali** [comment]
Was using the same seed and didn't notice, thank you so much! Just another question because I'm unsure as to how to structure this, but how do I pass more than one thing to the process being parallelized?

i.e., I have the following code:

```
from multiprocess import Pool
from simulation_rep import process_frame

# Defining the black-box function
def black_box_wilson(couplingA, speed):
    # For every point, replicate 5 times to get an average measure of what the variability is like, or the spread of correlation.
    # Number of replications
    replications = 5
    # Define a range from 0 -> replications
    frames_list = [couplingA, speed, np.arange(0, replications)]

    ############ PARALLELIZING THE 5 REPETITIONS
    max_pool = 5    
    with Pool(max_pool) as p:
        pool_outputs = list(
            tqdm(
                p.imap(process_frame,
                    frames_list),
                total=len(frames_list)
            )
        )
```
I want to pass couplingA and speed (static floats) as well as one value of the frames range (which has the replication index) to the function ` process_frame`. Process_frame looks as follows:

```
def process_frame(params_rep):
    return params_rep, simulate_parallel(params_rep)
```
where `simulate_parallel` is the function that actually needs `couplingA, speed` and one element of `rep` per replication. Is there any way to do this?

Thank you so much in advance, I hope this makes sense!! Sorry if it's an obvious question :)

**Comment by mmckerns** [comment]
I can't run your code, so I'll give a small example of what I think you want to do:

```
Python 3.8.16 (default, Dec  7 2022, 05:25:02) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> def add(x,y):
...   return x+y
... 
>>> import multiprocess as mp
>>> p = mp.Pool()
>>> p.starmap(add, zip(range(4), range(0,40,10)))
[0, 11, 22, 33]
```

If this answers your (first and second) question, please close the issue.

**Comment by Hana-Ali** [comment]
Thank you so much! It does :)
