### ISSUE TITLE
Multiprocess works where multiprocessing fails

### ISSUE THREAD

**Issue by enzbus** [uqfoundation/multiprocess#147]
Hello, this is not an issue but a request for information. I have a usecase (a bit difficult to explain in detail, sorry) in which `multiprocessing` fails with bugs that I don't understand, but I don't think are `pickle`-related. Instead I suspect it has to do with re-using existing worker processes (I use `Pool().map`). In particular I have an extension module that allocates some global memory space that could be corrupted if re-used. Simply replacing `multiprocessing` with `multiprocess` solves the bug. Can you help me understand why that could be? Does `multiprocess` treat worker processes differently than `multiprocessing`? Thank you!

**Comment by mmckerns** [comment]
`multiprocess` does not treat workers differently than `multiprocessing`... fundamentally there are two changes from `multiprocessing`: (1) `pickle` is replaced with `dill`, and (2) on the mac, the default context is different.

So, if you are on a mac...  I expect that your code may also work with `multiprocessing` if you were to change the `multiprocessing.context`.  If you aren't, then there are basically two other possibilities: the change in the pickler, or (3) if there's a bug in the version of `multiprocessing` you are using, then it would probably also show up in `multiprocess` given you used the corresponding version. 

Let me know if that answers your question.

**Comment by enzbus** [comment]
Yes, this happened on a mac, thank you! I'm not sure I'll manage to isolate the bug I was dealing with but it any case `multiprocess` solved it, thanks!
