### ISSUE TITLE
Security Policy

### ISSUE THREAD

**Issue by kontibbo** [uqfoundation/multiprocess#148]
I'm attempting to contact you using your security policy listed here: https://github.com/uqfoundation/.github/blob/main/SECURITY.md
The mail server listed appears to be offline. What is the best way to contact you if I wanted to discuss a potential security issue?

**Comment by kontibbo** [comment]
When attempting to send an email it bounces with the message:
`[mmckerns@uqfoundation.com](mailto:mmckerns@uqfoundation.com)`
`Remote Server returned '554 5.0.0 < #5.0.0 smtp; 5.4.7 - Delivery expired (message too old) '[Errno 61] Connection refused' (delivery attempts: 0)>`

Checked through mxtoolbox as well and could not connect using SMTP: https://mxtoolbox.com/SuperTool.aspx?action=smtp%3auqfoundation.com&run=toolpage

Is there any other method of contact we can use or a different email that works?

**Comment by mmckerns** [comment]
Whoops.  It's `mmckerns[@]uqfoundation.com`  That's a typo!

**Comment by mmckerns** [comment]
I'm going to close this, as things should work as expected now.
