### ISSUE TITLE
python 3.11+ wheel(s) for pypi?

### ISSUE THREAD

**Issue by timksf** [uqfoundation/multiprocess#149]
Hi,

is there a reason behind pypi only having wheels up to python version 3.10?
With python 3.11.3, pip installed the wheel for version 3.10, this version had some issues with fork_exec though.
Building the source manually for 3.11 worked fine.

Best, Tim

**Comment by mmckerns** [comment]
Hi Tim, the reason is that the latest release was a few days before python 3.11.0 was released, so 3.11 is not officially supported in the most recent release.  It does work from source, and we are about to cut a new release that will support 3.11.
