### ISSUE TITLE
ImportError: No module named _multiprocess (on AWS EC2)

### ISSUE THREAD

**Issue by kruhly** [uqfoundation/multiprocess#15]
I'm trying to install multiprocess into an ubuntu linux 14.04  anaconda environment on an aws ec2 instance.

Using pip install multiprocess executes successfully and installs 0.70.4

However, in ipython:

import multiprocess 

generates the folllowing:

---

ImportError                               Traceback (most recent call last)
<ipython-input-1-3643457f557d> in <module>()
----> 1 import multiprocess

/home/ubuntu/anaconda/envs/roa/lib/python2.7/site-packages/multiprocess/**init**.py in <module>()
     82 
     83 # This is down here because _multiprocessing uses BufferTooShort
---> 84 import _multiprocess as _multiprocessing
     85 
     86 #

ImportError: No module named _multiprocess

I'm using the same environment on the AWS EC2 instance as on my stand alone ubuntu 14.04 box where the same version was installed via cvxpy successfully (ie no import error).

Using which c++ generates

/usr/bin/c++

Using which g++ generates

/usr/bin/g++

Using which gcc generates

/usr/bin/gcc 

on both the AWS EC2 instance and my box where there is no issue.

Anything else I can try?

Thanks,

Rob

**Comment by mmckerns** [comment]
Usually I see your error when someone doesn't have a C compiler, or the PATH or PYTHONPATH is bad.  I've not built on AWS EC2, so I don't have experience there…

Maybe you can build with setup.py install, and look at (or share) the output?

**Comment by kruhly** [comment]
Thanks for the prompt response

Some output from attempts on AWS: 

Note () indicate the anaconda environment where  

pip install multiprocess 

was run. 

(root) -- also system python using sudo pip install

Downloading/unpacking multiprocess
  Downloading multiprocess-0.70.4.tgz (1.1MB): 1.1MB downloaded
  Running setup.py (path:/tmp/pip_build_ubuntu/multiprocess/setup.py) egg_info for package multiprocess
    
Downloading/unpacking dill>=0.2.5 (from multiprocess)
  Downloading dill-0.2.5.tgz (60kB): 60kB downloaded
  Running setup.py (path:/tmp/pip_build_ubuntu/dill/setup.py) egg_info for package dill
    
Installing collected packages: multiprocess, dill
  Running setup.py install for multiprocess
    building '_multiprocess' extension
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_SEM_OPEN=1 -DHAVE_FD_TRANSFER=1 -DHAVE_SEM_TIMEDWAIT=1 -Ipy2.7/Modules/_multiprocess -I/home/ubuntu/anaconda/include/python2.7 -c py2.7/Modules/_multiprocess/multiprocess.c -o build/temp.linux-x86_64-2.7/py2.7/Modules/_multiprocess/multiprocess.o
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_SEM_OPEN=1 -DHAVE_FD_TRANSFER=1 -DHAVE_SEM_TIMEDWAIT=1 -Ipy2.7/Modules/_multiprocess -I/home/ubuntu/anaconda/include/python2.7 -c py2.7/Modules/_multiprocess/socket_connection.c -o build/temp.linux-x86_64-2.7/py2.7/Modules/_multiprocess/socket_connection.o
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_SEM_OPEN=1 -DHAVE_FD_TRANSFER=1 -DHAVE_SEM_TIMEDWAIT=1 -Ipy2.7/Modules/_multiprocess -I/home/ubuntu/anaconda/include/python2.7 -c py2.7/Modules/_multiprocess/semaphore.c -o build/temp.linux-x86_64-2.7/py2.7/Modules/_multiprocess/semaphore.o
    gcc -pthread -shared build/temp.linux-x86_64-2.7/py2.7/Modules/_multiprocess/multiprocess.o build/temp.linux-x86_64-2.7/py2.7/Modules/_multiprocess/socket_connection.o build/temp.linux-x86_64-2.7/py2.7/Modules/_multiprocess/semaphore.o -L/home/ubuntu/anaconda/lib -lrt -lpython2.7 -o build/lib.linux-x86_64-2.7/_multiprocess.so
    
  Running setup.py install for dill
    changing mode of build/scripts-2.7/unpickle.py from 664 to 775
    changing mode of build/scripts-2.7/get_objgraph.py from 664 to 775
    
    changing mode of /home/ubuntu/anaconda/bin/unpickle.py to 775
    changing mode of /home/ubuntu/anaconda/bin/get_objgraph.py to 775
Successfully installed multiprocess dill
Cleaning up...

The (root) and system install work.

(cloned environment)

Collecting multiprocess
Collecting dill>=0.2.5 (from multiprocess)
Installing collected packages: dill, multiprocess
Successfully installed dill-0.2.5 multiprocess-0.70.4

The (cloned environment) install does not work. Same import error as initial bug report.

(new environment)
Installing collected packages: multiprocess, dill
  Running setup.py install for multiprocess
    building '_multiprocess' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_SEM_OPEN=1 -DHAVE_FD_TRANSFER=1 -DHAVE_SEM_TIMEDWAIT=1 -Ipy2.7/Modules/_multiprocess -I/usr/include/python2.7 -c py2.7/Modules/_multiprocess/multiprocess.c -o build/temp.linux-x86_64-2.7/py2.7/Modules/_multiprocess/multiprocess.o
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_SEM_OPEN=1 -DHAVE_FD_TRANSFER=1 -DHAVE_SEM_TIMEDWAIT=1 -Ipy2.7/Modules/_multiprocess -I/usr/include/python2.7 -c py2.7/Modules/_multiprocess/socket_connection.c -o build/temp.linux-x86_64-2.7/py2.7/Modules/_multiprocess/socket_connection.o
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_SEM_OPEN=1 -DHAVE_FD_TRANSFER=1 -DHAVE_SEM_TIMEDWAIT=1 -Ipy2.7/Modules/_multiprocess -I/usr/include/python2.7 -c py2.7/Modules/_multiprocess/semaphore.c -o build/temp.linux-x86_64-2.7/py2.7/Modules/_multiprocess/semaphore.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/py2.7/Modules/_multiprocess/multiprocess.o build/temp.linux-x86_64-2.7/py2.7/Modules/_multiprocess/socket_connection.o build/temp.linux-x86_64-2.7/py2.7/Modules/_multiprocess/semaphore.o -lrt -o build/lib.linux-x86_64-2.7/_multiprocess.so
    
    
    -----------------------------------------------------------------------
    WARNING: The C extensions could not be compiled
    -----------------------------------------------------------------------
    
    Maybe you do not have a C compiler installed on this system?
    The reason was:
      File "<string>", line 1, in <module>
    
      File "/tmp/pip_build_ubuntu/multiprocess/setup.py", line 327, in <module>
        msg = BUILD_WARNING % '\n'.join(traceback.format_stack())
    
    
    This is just a warning as most of the functionality will work even
    without the updated C extension.  It will simply fallback to the
    built-in _multiprocessing module.  Most notably you will not be able to use
    FORCE_EXECV on POSIX systems.  If this is a problem for you then please
    install a C compiler or fix the error(s) above.
    -----------------------------------------------------------------------
    
    
    error: could not create '/usr/local/lib/python2.7/dist-packages': Permission denied
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_ubuntu/multiprocess/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-yfo99H-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/multiprocess

copying py2.7/multiprocess/pool.py -> build/lib.linux-x86_64-2.7/multiprocess

copying py2.7/multiprocess/queues.py -> build/lib.linux-x86_64-2.7/multiprocess

copying py2.7/multiprocess/managers.py -> build/lib.linux-x86_64-2.7/multiprocess

copying py2.7/multiprocess/heap.py -> build/lib.linux-x86_64-2.7/multiprocess

copying py2.7/multiprocess/synchronize.py -> build/lib.linux-x86_64-2.7/multiprocess

copying py2.7/multiprocess/reduction.py -> build/lib.linux-x86_64-2.7/multiprocess

copying py2.7/multiprocess/util.py -> build/lib.linux-x86_64-2.7/multiprocess

copying py2.7/multiprocess/process.py -> build/lib.linux-x86_64-2.7/multiprocess

copying py2.7/multiprocess/forking.py -> build/lib.linux-x86_64-2.7/multiprocess

copying py2.7/multiprocess/connection.py -> build/lib.linux-x86_64-2.7/multiprocess

copying py2.7/multiprocess/sharedctypes.py -> build/lib.linux-x86_64-2.7/multiprocess

copying py2.7/multiprocess/__init__.py -> build/lib.linux-x86_64-2.7/multiprocess

creating build/lib.linux-x86_64-2.7/multiprocess/dummy

copying py2.7/multiprocess/dummy/connection.py -> build/lib.linux-x86_64-2.7/multiprocess/dummy

copying py2.7/multiprocess/dummy/__init__.py -> build/lib.linux-x86_64-2.7/multiprocess/dummy

running build_ext

building '_multiprocess' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/py2.7

creating build/temp.linux-x86_64-2.7/py2.7/Modules

creating build/temp.linux-x86_64-2.7/py2.7/Modules/_multiprocess

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_SEM_OPEN=1 -DHAVE_FD_TRANSFER=1 -DHAVE_SEM_TIMEDWAIT=1 -Ipy2.7/Modules/_multiprocess -I/usr/include/python2.7 -c py2.7/Modules/_multiprocess/multiprocess.c -o build/temp.linux-x86_64-2.7/py2.7/Modules/_multiprocess/multiprocess.o

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_SEM_OPEN=1 -DHAVE_FD_TRANSFER=1 -DHAVE_SEM_TIMEDWAIT=1 -Ipy2.7/Modules/_multiprocess -I/usr/include/python2.7 -c py2.7/Modules/_multiprocess/socket_connection.c -o build/temp.linux-x86_64-2.7/py2.7/Modules/_multiprocess/socket_connection.o

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_SEM_OPEN=1 -DHAVE_FD_TRANSFER=1 -DHAVE_SEM_TIMEDWAIT=1 -Ipy2.7/Modules/_multiprocess -I/usr/include/python2.7 -c py2.7/Modules/_multiprocess/semaphore.c -o build/temp.linux-x86_64-2.7/py2.7/Modules/_multiprocess/semaphore.o

x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/py2.7/Modules/_multiprocess/multiprocess.o build/temp.linux-x86_64-2.7/py2.7/Modules/_multiprocess/socket_connection.o build/temp.linux-x86_64-2.7/py2.7/Modules/_multiprocess/semaphore.o -lrt -o build/lib.linux-x86_64-2.7/_multiprocess.so

running install_lib

creating /usr/local/lib/python2.7/dist-packages





-----------------------------------------------------------------------

WARNING: The C extensions could not be compiled

-----------------------------------------------------------------------



Maybe you do not have a C compiler installed on this system?

The reason was:

  File "<string>", line 1, in <module>



  File "/tmp/pip_build_ubuntu/multiprocess/setup.py", line 327, in <module>

    msg = BUILD_WARNING % '\n'.join(traceback.format_stack())





This is just a warning as most of the functionality will work even

without the updated C extension.  It will simply fallback to the

built-in _multiprocessing module.  Most notably you will not be able to use

FORCE_EXECV on POSIX systems.  If this is a problem for you then please

install a C compiler or fix the error(s) above.

-----------------------------------------------------------------------





running install

running build

running build_py

running install_lib

creating /usr/local/lib/python2.7/dist-packages

error: could not create '/usr/local/lib/python2.7/dist-packages': Permission denied

Unsuccessful install.

There looks two be two cases where permission is denied.

This directory does not exist on AWS and it does not exist my local ubuntu 14.04 installation where there is no issue. 

I hope this helps.

Rob

**Comment by mmckerns** [comment]
There's definitely the error that the C extensions cannot be compiled, which is causing you to not be able to import `_multiprocess` (because it doesn't exist).  I've never seen a `Permission denied` error in trying to build `dist-packages`… but a quick google search turns up some results that might be relevant:

- http://serverfault.com/questions/526594/
- http://stackoverflow.com/questions/21093002/
- http://askubuntu.com/questions/524044/

I couldn't tell from what you posted above if you were using `sudo` in your user installs, or if not using `sudo` you were using `--user` or `--prefix` or something similar (I assume you weren't).  Let me know if that helps or not.

**Comment by kruhly** [comment]
Hi 
Sorry for the slow reply. We are also having issues with a web framework on AWS.

For the new environment and cloned environment, I was installing without sudo so it would be installed for the user within the virtual environment. It should not have been installing globally  but for some reason it was for the new environment. However, at the moment that is not my biggest concern.

My biggest concern is for the cloned environment where the install seems to go well but does not work:
****************************************************
Collecting multiprocess
Collecting dill>=0.2.5 (from multiprocess)
Installing collected packages: dill, multiprocess
Successfully installed dill-0.2.5 multiprocess-0.70.4

The (cloned environment) install does not work. Same import error as initial bug report.
**************************************************************************************************

Because the root environment compiles _multiprocess, I know the compiler is there and working. For the cloned environment also seems like there is a path issue, but different than the new environment global path issue, since _multiprocess does not get built. 

I will let you know if I make any progress.

THanks for your help.

**Comment by mmckerns** [comment]
I have not installed `pathos` on AWS, so you are in unknown territory for me.  However, I can say that if `multiprocess` fails to compile/install the `_multiprocess` module, the build *does* *not* fail.  Perhaps it should.

**Comment by mmckerns** [comment]
Note see #8 and #10.

**Comment by mmckerns** [comment]
This is no longer relevant as support for python 2 has been dropped.
