### ISSUE TITLE
Issue with multiprocess and Python 3.11

### ISSUE THREAD

**Issue by cheikhgwane** [uqfoundation/multiprocess#152]
Hi, 
I noticed an issue when trying to use multiprocess on python 3.11. When running the following code : 

```console
Python 3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from multiprocess import get_context
>>> context =  get_context("spawn")
>>> pool = context.Pool()
```

![image](https://github.com/uqfoundation/multiprocess/assets/25453621/8b076310-ead1-4c52-81da-73be6ef87d28)

I'm using multiprocess multiprocess 0.70.14. The same code on python3.10 works.

Hopefully that's clear, let me know if you need more information.

Thanks a lot,
Cheikh

**Comment by mmckerns** [comment]
Python 3.11 is not supported in `multiprocess` 0.70.14 as it came out before 3.11.0 was released.  A new release is imminent.  Can you try `multiprocess` master?  If it works, I'll close this as a duplicate of #149 .

**Comment by cheikhgwane** [comment]
> Python 3.11 is not supported in `multiprocess` 0.70.14 as it came out before 3.11.0 was released. A new release is imminent. Can you try `multiprocess` master? If it works, I'll close this as a duplicate of #149 .

Thanks for your answer, I'll let you know.

**Comment by cheikhgwane** [comment]
HI @mmckerns , 
multiprocess from master works. I think we'll try to use it until a new release is done. 
Thank you
