### ISSUE TITLE
Always builds without extensions

### ISSUE THREAD

**Issue by juliangilbey** [uqfoundation/multiprocess#155]
I just noticed that these lines in `setup.py`:
https://github.com/uqfoundation/multiprocess/blob/2d321628ba08d10fe0d9c0ac5eb962e91f8532ab/setup.py#L293-L302
mean that there is never an attempt to build the extensions.  I assume that the first `run_setup` line is intended to be `run_setup()` or `run_setup(True)`?

**Comment by juliangilbey** [comment]
Ah, and when I did try building the extension for Python 3.11 (by making the above suggested change), the compilation failed due to an error in the C code.

**Comment by mmckerns** [comment]
Yes, the extensions are a bit of an artifact currently.  The code there is not built because it is currently identical to `_multiprocessing` -- so there's no need to build it.

**Comment by mmckerns** [comment]
I'm going to close this. Thanks for looking into this -- I should probably clean it up a bit.
