### ISSUE TITLE
feat: allow more iterables in `Pool.map()`

### ISSUE THREAD

**Issue by ankostis** [uqfoundation/multiprocess#179]
The [`Pool.map()` method](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Executor.map) of the `multiprocessing` standard module supports more than one argument in its `map()` method since it mimics the [build-in `map(func, *iterables)` function](build-in `map(func, *iterables)` function).
Shouldn't this library mimic also this API?

**Comment by mmckerns** [comment]
So you linked the `map` method in the `concurrent.futures` module, which works like the `starmap` method in `multiprocessing`. Here's [`map` from `multiprocessing`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.pool.Pool.map) -- which only allows a single iterable.  If you want multiple iterables, you can use the [`starmap` method](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.pool.Pool.starmap), or the [`map` method from `pathos`](https://pathos.readthedocs.io/en/latest/pathos.html#pathos.multiprocessing.ProcessPool.map), which is intended to mimic python's built-in `map` interface.

The short answer is no.  Also, if you like the `concurrent.futures` API, this is something that `pathos` has an open ticket to further adopt.
