### ISSUE TITLE
Is it recommended to use multiprocess with gevent's socket patch?

### ISSUE THREAD

**Issue by pcdinh** [uqfoundation/multiprocess#24]
Hi,

I am working on a non-blocking I/O gevent-powered web application that is required to launch a child process to handle a CPU-intensive task which can be crashed randomly because of bugs in the underlying C/C++ code.

However, Python's standard multiprocessing has defined its own socket that makes it incompatible with gevent's patch. As a result, the following code does not work

```
from gevent.monkey import patch_all
patch_all()
from multiprocessing import Process, Pipe

def test_document(conn, local_path):
    try:
        file_utils.test_document(local_path)
    except BaseException as e:
        conn.send(e)
    else:
        conn.send("done")
    conn.close()

parent_conn, child_conn = Pipe()
p = Process(target=test_document, args=(child_conn, local_path,))
p.start()
try:
    message = None
    # Broken because of gevent
    message = parent_conn.recv() # An IOError (Resource temporarily unavailable) will be thrown
except:
    # Always get a IOError, message will be never returned
   pass
```

The solution to this issue is to unpatch it which makes multiprocessing code work.

https://github.com/liujingchen/fixgevent

However, it forces my application to be blocked on I/O again.

What about `multiprocess`? Can it handle the issue or I need to implement a work-around?

Thanks

**Comment by mmckerns** [comment]
Sorry this question slipped through the cracks and you have not received a reply earlier.

`multiprocess` is a fork of `multiprocessing`, so I expect that if you are seeing an issue with `multiprocessing` defining it's own socket, than you'll also see the issue in `multiprocess`, as the code is nearly identical (the exception being that `multiprocess` uses `dill` as opposed to `pickle`).

Let me know if this issue can be closed, or if you had more to add.

**Comment by mmckerns** [comment]
I'm going to close this issue since there is not activity after my response.  Please feel free to reopen this ticket if you have further to add.

**Comment by zhongwm** [comment]
Can usage can be replaced by replacing Pipe with Queue, then you can both have socket monkey patched. Would be good option if you are not dealing with a legacy code made heavy use of Pipe.
