### ISSUE TITLE
build sphinx docs and upload to readthedocs

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/multiprocess#39]
Build sphinx docs for `multiprocess`.

This is a little weird, as the docs are overwhelmingly the same as the python standard library `multiprocessing`... and in addition, `multiprocess` has a slightly different version for each minor version of python.

**Comment by Christiaanvv** [comment]
Any update on how to read the docs?

**Comment by mmckerns** [comment]
@Christiaanvv: you can literally read the `multiprocessing` docs as a workaround for now.  The code is 99% the same.  I set up sphinx and attempted to load to readthedocs, and the build fails.  I still need to work out why it's failing (on the C code).

**Comment by fjsj** [comment]
Probably that's why http://multiprocess.rtfd.io link is broken?

**Comment by mmckerns** [comment]
@fjsj: Correct. My above comment still stands, the build of the docs on the C code is still failing.

**Comment by laszukdawid** [comment]
Even though, as you mentioned, docs are almost the same as for `multiprocessing` there is a slightly bigger issue with this ticket. It's mainly that README (and other internet pages) point to https://multiprocess.readthedocs.io/ as the best starting point:

> Probably the best way to get started is to look at the documentation http://multiprocess.rtfd.io.

Given that the ticket has been opened over two years ago, maybe we could update Readme in the mean time?

**Comment by mmckerns** [comment]
Support for python 2.7 is being discontinued, and python 3.x doesn't require any C code... so, as soon as support for 2.7 is dropped, the sphinx docs should build.  The plan is to drop support for 2.7 by the next release, which should happen by year's end.  The README and other docs are generally updated upon when a release is posted.  So, the resolution is probably going to be that support for 2.7 is dropped, and that results in the sphinx docs working.
