### ISSUE TITLE
`multiprocess.pool` not available after just `import multiprocess`

### ISSUE THREAD

**Issue by jason-neal** [uqfoundation/multiprocess#45]
I was trying to add typing to a function that can take either an integer or a `multiprocess.Pool().`
in the case of the integer it would star a Pool itself.
```
from typing import Union
import multiprocess

def foo( procs : Union[int, multiprocess.pool.Pool]):
    pass
```
This however fails with 
`AttributeError: module 'multiprocess' has no attribute 'pool'`

if I either run `import multiprocess.pool`
```
import multiprocess.pool
multiprcess.pool
```
or if I use  `multiprocess.Pool()`
```
import multiprocess
multiprocess.Pool()
multiprcess.pool
```
They work.
but 
```
import multiprocess
multiprcess.pool
>> AttributeError: module 'multiprocess' has no attribute 'pool'
```
gives the error.

My question is this the expected behavior?

**Comment by mmckerns** [comment]
Yes, this is expected behavior.  The intent is to use `multiprocess.Pool`, not `multiprocess.pool.Pool`.  Is there a need for the latter?

**Comment by jason-neal** [comment]
Ok. 
The two uses I was using multiprocess.pool.Pool for were instance checking and type annotation. 
Specifically in modules that do not specifically use/call multiprocess.Pool() themselves.

For these two I will just need to specifically import `mulitiprocees.pool.Pool`
```
In [1]: import multiprocess
In [2]: x = 1
In [3]: isinstance(x, multiprocess.pool.Pool())
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-79d417f372e8> in <module>()
----> 1 isinstance(x, multiprocess.pool.Pool())

AttributeError: module 'multiprocess' has no attribute 'pool'
```
or in type annotation.

```
In [1]:  import multiprocess
In [2]: def x(proc:multiprocess.pool.Pool):
   ...:     pass
   -------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-1ec2462f09f5> in <module>()
----> 1 def x(proc:multiprocess.pool.Pool):
      2     pass

AttributeError: module 'multiprocess' has no attribute 'pool'
```

**Comment by mmckerns** [comment]
I believe the above does work if you `import multiprocess.pool` first.

```
>>> import multiprocess.pool
>>> multiprocess.pool.Pool
<class 'multiprocess.pool.Pool'>
>>> isinstance(1, multiprocess.pool.Pool)
False
```

**Comment by jason-neal** [comment]
Yes `import multiprocess.pool` also works.
Out of my naivety I was expecting the `multiprocess.pool`(lowercase) to be available.
Avoiding confusion with `multiprocess.Pool` is valid for it not to be

Thanks.
