### ISSUE TITLE
register issue on Python IDE

### ISSUE THREAD

**Issue by 229668880** [uqfoundation/multiprocess#46]
Hi, this is my codes:

from multiprocess import Queue
q = Queue()  
BaseManager.register('getq',callable=lambda:q)  
server=BaseManager(address=('127.0.0.1',5009),authkey=b'abc')   
server.start()                                      
x=server.getq()      # Here I got an error

RemoteError:
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\Anaconda3\lib\site-packages\multiprocess\managers.py", line 195, in handle_request
    result = func(c, *args, **kwds)
  File "E:\Anaconda3\lib\site-packages\multiprocess\managers.py", line 351, in create
    obj = callable(*args, **kwds)
  File "<ipython-input-144-4d5a1e1f91e9>", line 1, in <lambda>
NameError: name 'q' is not defined

**Comment by 229668880** [comment]
I still got the same error when I do like this:

def test():
   global q
   return q

BaseManager.register('getq',callable=test)

**Comment by mmckerns** [comment]
Sorry for the delay.  I tried your code, and it seems to work for me.  What version of `multiprocess`, `python`, and what OS are you using?
```
Python 3.6.8 (default, Dec 30 2018, 13:04:41) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from multiprocess import Queue
>>> from multiprocess.managers import BaseManager
>>> q = Queue()
>>> BaseManager.register('getq', callable=lambda :q) 
>>> server = BaseManager(address=('127.0.0.1',5009),authkey=b'abc')
>>> server.start()
>>> x = server.getq()
>>> x
<AutoProxy[getq] object, typeid 'getq' at 0x1029bff60>
>>> 
```
I tested all versions of python 2.7 - 3.7, with the most recent `multiprocess` and OSX, and could not reproduce the error you are seeing.

**Comment by 229668880** [comment]
Thank your. I have solved this issue.

**Comment by mmckerns** [comment]
Ok, great.  Thanks for posting.
