### ISSUE TITLE
Issue on Ubuntu 18.04 Amazon Instance 

### ISSUE THREAD

**Issue by sagarsadhu** [uqfoundation/multiprocess#53]
![error1](https://user-images.githubusercontent.com/21293079/56957980-7d07a500-6b66-11e9-8d53-c619ef4581c8.PNG)

In the picture , I showed you how I used multiprocessing to 'run'. The error which I get is

Exception in thread Thread-3:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/usr/lib/python2.7/multiprocessing/pool.py", line 392, in _handle_results
task = get()
File "/home/ubuntu/.local/lib/python2.7/site-packages/mysql/connector/errors.py", line 194, in init
'msg': self.msg.encode('utf8') if PY2 else self.msg
AttributeError: 'int' object has no attribute 'encode'

Details:
OS : ubuntu 18.04

If you need any additional details, please ask me

**Comment by mmckerns** [comment]
@sagarsadhu: It would help greatly for you to post a simple fully encapsulated code snippet that demonstrates the error you are seeing.  As I can't run your code, it's much harder to help.  If you can post code that reproduces your error, that would be most helpful.

As is, I have a few questions.  From the traceback, it seems you are using `multiprocessing` (i.e. from the STL python) and not `multiprocess`.  Which one are you using?  Second, it also seems the error you are seeing is from `mysql.connector.errors`. From your posted code, it's impossible to know what your function `run` or `listdir` does... hence, I can't tell what is being sent to `p.map`.  What is the input and output of `run`?   Where is the `mysql` code that is indicated in the traceback?

**Comment by sagarsadhu** [comment]
First, I apologize for not checking my program correctly. This is an issue from mysql-connector module. I fixed it. 

I will close the issue. 

I appreciate you for spending time on this.

**Comment by mmckerns** [comment]
@sagarsadhu: no problem.  Thanks for reporting.
