### ISSUE TITLE
How to use Multiprocessing in Pandas?

### ISSUE THREAD

**Issue by Ritesh260397** [uqfoundation/multiprocess#55]
when i use multiprocessing in normal program its working fine in pandas,but when i use this multiprocessing time is not reducing.

[import multiprocessing
import time
import pandas as pd
start=time.time()

def square(df1):
    df1['M_threading'] = df1['M_Invoice_type']
def multiply(df4):
    df4['M_threading'] = df4['M_Invoice_type']

if __name__ == '__main__':
    df = pd.read_excel("filename.xlsx")
    df1 = df.loc[df['M_Invoice_type'] == 'B2B']
    df4 = df.loc[df['M_Invoice_type'] == 'B2BUR']
    p=multiprocessing.Process(target=square,args=(df,))
    p1 = multiprocessing.Process(target=multiply, args=(df,))
    p.start()
    p1.start()
    p.join()
    p1.join()
    print("Done")
    end=time.time()
    print(end-start)](url)

I expect the output time of code 25sec, but the actual output is 51sec.

**Comment by mmckerns** [comment]
@Ritesh260397: Note that you are using `multiprocessing`.  This is the GitHub for `multiprocess`.  Please reopen this ticket if you actually have a typo in the module name above.
