### ISSUE TITLE
Infinite loop in setup.py

### ISSUE THREAD

**Issue by llchan** [uqfoundation/multiprocess#59]
The fall-back-to-previous-version logic in setup.py can potentially infinite loop due to floating point precision issues.  For example, try running the multiprocess-0.70.7 tag with python 3.8.

One solution would be to use `decimal.Decimal` and bound the loop, but I don't think that's a good long term solution because once we move onto two-digit minor versions, then suddenly 3.11 will not be able to find 3.10.  What it should really do is fix the major version and decrement minor versions as integers until a match is found (or it goes negative).

**Comment by mmckerns** [comment]
point taken.
