### ISSUE TITLE
Pool.map() behaviour on PyPy

### ISSUE THREAD

**Issue by Nitrooo** [uqfoundation/multiprocess#62]
In my project I'm using `pathos.multiprocessing.ProcessPool.map` on `PyPy3.6 v7.1.1` running on `Linux Mint 19.1 64 bit` and I'm running into unexpected high memory usage that ends up in memory thrashing. `map()` takes a list of items that are evaluated using a very large (~1-2 GB ) read only data structure created by the parent process at start before creating the pool and globally shared to the worker processes. At some point in the middle of the `map` call, after that a few items of the list are evaluated, the memory usage of the processes explodes.
Now, consider this script:
```
import os
import random

SIZE = 10000000
PROCESSES = 4

print('generating global shared data...')
data = [random.random() for _ in range(SIZE)]


def job(_):
    pid = os.getpid()
    print(f'process {pid}: reading...')
    for n in data:
        pass
    print(f'process {pid}: done')


def main():
    import multiprocess as mp
    pool = mp.Pool(PROCESSES)
    print('running pool.map()...')
    pool.map(job, [None] * PROCESSES)
    print('done')


if __name__ == '__main__':
    main()
```
Output and behaviour on `PyPy3` :

```
generating global shared data...
running pool.map()...     <--- long wait and heavy memory usage increase/decrease
process 8644: reading...
process 8644: done        <--- long wait and heavy memory usage increase/decrease
process 8645: reading...
process 8645: done        <--- long wait and heavy memory usage increase/decrease
process 8646: reading...
process 8646: done        <--- long wait and heavy memory usage increase/decrease
process 8647: reading...
process 8647: done
done
```
Output on `CPython 3.7.3`:
```
generating global shared data...
running pool.map()...
process 10594: reading...
process 10595: reading...
process 10596: reading...
process 10597: reading...
process 10594: done
process 10596: done
process 10597: done
process 10595: done
done
```
and no waiting or high memory usage. I get the same correct and expected output and behaviour when I switch to `multiprocessing` on both `PyPy` and `CPython 3.7.3`. Bad things happen only on `multiprocess`+`PyPy`. Decreasing `SIZE` makes things go smoother, so it's definitely related to the big size of `data`.
After having read an [article](https://llvllatrix.wordpress.com/2016/02/19/python-vs-copy-on-write/) I thought I was seeing the result of some kind of unnecessary pickling or ["copy-on-read" issue](https://instagram-engineering.com/dismissing-python-garbage-collection-at-instagram-4dca40b29172) but even when I comment out:
```
    # for n in data:
    #     pass
```
I get the same bad result on `multiprocess`+`PyPy`, so (with my very limited experience in Python) I would rule those hypotheses out.
It's worth noting what happens when you increase the size of the list.
Changing to `pool.map(job, [None] * 100)` gives:
```
generating global shared data...
running pool.map()...        <--- long wait and heavy memory usage increase/decrease
process 12572: reading...
process 12572: done
process 12572: reading...
process 12572: done
process 12572: reading...
process 12572: done
process 12572: reading...
process 12572: done
process 12572: reading...
process 12572: done
process 12572: reading...
process 12572: done
process 12572: reading...
process 12572: done        <--- long wait and heavy memory usage increase/decrease
process 12573: reading...
process 12573: done
process 12573: reading...
process 12573: done
process 12573: reading...
process 12573: done
process 12573: reading...
process 12573: done
process 12573: reading...
process 12573: done
process 12573: reading...
process 12573: done
process 12573: reading...
process 12573: done        <--- long wait and heavy memory usage increase/decrease
.
.
.
```
It looks like it has to do with the chunking `map` does on the iterable parameter to split the job and distribute to the workers, and I say so also because the heavy memory thrashing in my project happens right after the very first chunks of the list are processed by each child process. Also note that the script below, that uses `Process` instead of `Pool`, works fine:
```
import os
import random

SIZE = 10000000
PROCESSES = 4

print('generating global shared data...')
data = [random.random() for _ in range(SIZE)]


def job(_):
    pid = os.getpid()
    print(f'process {pid}: reading...')
    for n in data:
        pass
    print(f'process {pid}: done')


def main():
    import multiprocess as mp

    for index in range(PROCESSES):
        process = mp.Process(target=job, args=(None,))
        process.start()


if __name__ == '__main__':
    main()
```
@mmckerns I would like to dig deeper into this issue, because I really need `PyPy`+`pathos`(or at least `multiprocess`) in my project, but maybe you have an idea on where to look at and what could be the culprit. As long as I'm not missing something obvious.

**Comment by mmckerns** [comment]
@Nitrooo: I have adding support for `pypy` on my list, but have not had time yet.
Two things I do/use are `dill.detect.trace` to trace pickling, and `pathos.profile` to profile jobs on other processes.  That's where I'd start.  However, fundamentally, what needs to happen is for me/someone to take a pure python implementation of multiprocessing, and then make all the same changes that I've made to swap in `dill`.

**Comment by Nitrooo** [comment]
@mmckerns thanks.
Just by turning on `dill`'s tracing I was able to find that on `PyPy` a lot more stuff seems to be pickled for every chunk. I'm not sure about the meaning of `#` and the numbers in the alphanumeric codes at the beginning of every debug line, but this is a string that is printed when running on `PyPy`, and not on `CPython`. I assume it's a pickled dictionary:
`D1: <dict.__repr__ of {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x00007fe88575fb78>, '__spec__': None, '__builtins__': <module 'builtins' (built-in)>, '__annotations__': {}, '__file__': '/home/nitrooo/PycharmProjects/mem_test/mem_test.py', '__cached__': None, 'os': <module 'os' from '/home/nitrooo/PycharmProjects/mem_test/pypy_venv/lib-python/3/os.py'>, 'random': <module 'random' from '/home/nitrooo/PycharmProjects/mem_test/pypy_venv/lib-python/3/random.py'>, 'dill': <module 'dill' from '/home/nitrooo/PycharmProjects/mem_test/pypy_venv/site-packages/dill/__init__.py'>, 'SIZE': 10, 'PROCESSES': 4, 'data': [0.8901946435403693, 0.8957613341294107, 0.3726616002868305, 0.1019347141440391, 0.44483877448013176, 0.972849172447508, 0.5084683021679588, 0.3371791543823687, 0.8723552017240117, 0.8542517686592163], 'job': <function job at 0x00007fe8854171a0>, 'main': <function main at 0x00007fe8854af2e0>}>`

As you can see it contains the `data` list. 
So, if I understand correctly making `multiprocess` fully compatible with `PyPy` it's not about fixing the current code but completely replacing it, right?

**Comment by mmckerns** [comment]
I have added full `pypy` support for `multiprocessing` in this commit: https://github.com/uqfoundation/multiprocess/commit/8ecf01a567f661717824800f99b74c6dacabf7f1

I'm also going to make `chunksize` available, and this may also help.  Let me know if this changes this ticket, etc.

**Comment by mmckerns** [comment]
By the way... in testing `multiprocess` for `pypy36` versus `multiprocessing` for `pypy36`, I've found that there's a semaphore leak in `multiprocess` that is also present in `multiprocessing` for `pypy36`.   It is not present in `pypy37` for either.  As `pypy` has discontinued support for `3.6`, and we will do the same here soon, I'm going to close this ticket.

**Comment by lqtrung1998** [comment]
Hello, I'm still facing this issue on an `Debian GNU/Linux 10 (buster)` machine with the multiprocess version `0.70.14` and `python 3.7`.  
```
import os
import random
import multiprocess as mp
import time
import numpy as np
import psutil

def memory_usage():
    current_process = psutil.Process()
    memory = current_process.memory_info().rss
    return (int(memory / (1024 * 1024)), "MB")
    
def job(_):
    pass

def main():
    print('running pool.map()...')
    for i in range(10):
        s = time.time()
        pool = mp.Pool(10)
        pool.map(job, [None] * 100)
        print(f'Loop: {i} takes:', time.time() -s)
    print('done')


if __name__ == '__main__':
    SIZE = 100000*3000
    print('generating global shared data...')
    
    #1 Store data as list. 
    # ~Output time per loop: 1.3 -> 1.6 seconds
    # data = [random.random() for _ in range(SIZE)] 
    
    #2 Store data as np array, x5 length to make the memory similar to that in #1.  
    # ~Output time per loop: 0.1 seconds
    data = np.random.rand(SIZE*5)                 
    
    #3 Empty ~ Output time per loop: 0.02 seconds
    # data = []                                    

    print('Data length:', len(data))
    print('Memory usage:', memory_usage())
    print('Done generating global shared data...')
    
    ## Runing main
    main()
```

The multiprocessing start method should be fork by default for Linux I believe. So I think, in this script, the `data` shouldn't  be copied to the child processes because of the Copy on Write feature and `data` is not referred at all in the multiprocessing target function.

But after running the script, it takes quite a long time to run each loop (1.3 -> 1.6 seconds), as if the data is copied to each child process. Interestingly, if we use numpy array, even with the same memory usage, the time for each loop is much better (0.1 seconds) ~ might be explained by [this](https://stackoverflow.com/questions/65981307/how-does-numpy-avoid-copy-on-access-on-child-process-from-gc-reference-counting#:~:text=Since%20they%20don%27t%20share,and%20therefore%20never%20get%20copied.)

Any idea ?

Thank you

**Comment by mmckerns** [comment]
@lqtrung1998: Yes, that's to be expected for a `numpy` `array` as the python portion is very light... basically a pointer with some metadata.  What's the issue that you are facing? The code is running slower than expected, or you are eating up a lot of memory, or ?  Note that this question is with regard to the behavior of `map` on `pypy`... and it seems that you are using `python`... so I think it might be better for you to open a new issue.

**Comment by lqtrung1998** [comment]
It seem to me that the `data` is copied to each process even though it is not referenced at all in the multiprocessing function because it takes quite a long time for each loop.

I also tried to use this `job` function below instead. This function modifies the `data`, so if I'm not wrong, the entire data must be copied to each process. But the time for each loop in this case is also the same ~1.3 -> 1.6s ... This makes me feel like my previous point is correct ....
```
def job(_):
    data[1] = 0 
    pass
```
So my question is: Is the `data` copied to each process during pool initialization ? .... This shouldn't be expected right? because the `data` is not referenced at all in the multiprocessing function  .....

Thank you.

**Comment by mmckerns** [comment]
The serialization of a python function requires a `globals` namespace to be stored, along with other items that are required to construct a function. Thus, anything in the namespace of the function might be pickled along with the function.  If `data` is not referred to by the function, you can try using `dill.settings['recurse'] = True`, which should only store the objects from globals that the function refers to.
