### ISSUE TITLE
PyCharm fails to find "Process"

### ISSUE THREAD

**Issue by sla-te** [uqfoundation/multiprocess#69]
Thanks for this wonderful library, which fixed a terrible pickle problem with my multiprocessing app.

I wanted to report that PyCharm for some reason fails to find "Process"
![image](https://user-images.githubusercontent.com/22568014/96353357-6b53ed80-10cb-11eb-9b59-0e975a5c75e1.png)

**Comment by mmckerns** [comment]
Which version of python, which version of multiprocess, and which OS are you using?

**Comment by chwba** [comment]
Windows 10 - 2004 - Python 3.9 - multiprocess v 0.70.10

**Comment by chwba** [comment]
Any news? In the meantime I found, that of course `from multiprocess.queues import Queue` works of course and one could do `from multiprocess.process import BaseProcess`, would that be correct?

**Comment by frozenranger** [comment]
Yup I got the same problem on pycharm 2020.3

**Comment by frozenranger** [comment]
same problem here, python 3.7, windows 10, pycharm 2020.3.... should we report this to the pycharm team?

**Comment by frozenranger** [comment]
luckily it appears that it still works! just this funny bug

**Comment by LarsHill** [comment]
Same issue here. Python 3.8.5, PyCharm 2020.2, multiprocess 0.70.10.

**Comment by artemgur** [comment]
Same issue. Python 3.10.7, PyCharm 2022.3.1, multiprocess 0.70.14

**Comment by mmckerns** [comment]
Thanks everyone for reporting. Unfortunately, there isn't anything that can be done with regard to `multiprocess`. 

It seems like it's `PyCharm` messing with either the default `multiprocess` `context` or `multiprocess.__init__`.   So.... anything in the default context (i.e. importable directly from the module) is actually located in `multiprocess.context`... so you should be able to import from there.

This should probably be reported to the `PyCharm` developers.  I'm going to close this as there's nothing that can be done wrt `multiprocess`.
