### ISSUE TITLE
Remove need for freeze_support on windows?

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/multiprocess#7]
freeze_support is required on windows, is it possible to remove the need to use it?

**Comment by janssen** [comment]
Um, what need for freeze_support?  The documentation (for 2.7) mentions freezeSupport(), but not freeze_support(), and it seems to be optional there (for normal command-line use).

**Comment by janssen** [comment]
Ah, found it.  Never mind.

**Comment by mmckerns** [comment]
let's say the answer is "no"
