### ISSUE TITLE
Multiprocess not starting

### ISSUE THREAD

**Issue by savage-eagle** [uqfoundation/multiprocess#74]
Hi, inside a new threading running I'm trying to use the multiprocess for a new class to run and having some durty errors with dill (https://pastebin.com/8qBfvJyg)

```
from multiprocess import Process

print("Before Class")
operation = Operation(info, self, self.__kernel)

print("After Class")
process = Process(target=operation.run, args=())
process.start()
```

The snippet code is this above, I pass thoses arguments to initialize operation class
`<class 'dict'> <class 'core.orders.Orders'> <class 'core.kernel.Kernel'>`

Any idea on what that could be?

Thanks.

Regards,
Savage.

**Comment by mmckerns** [comment]
Sorry for the slow reply.  You've not provided enough information to enable me to give you a good response.  It'd be nice to have a standalone code example that can reproduce what you are seeing.  The error in your pastebin says it stems from trying to serialize a socket, which I believe does not serialize -- see: https://bugs.python.org/issue30829.

Please, if you could, update this issue with sufficient information, or close the issue.

**Comment by mmckerns** [comment]
I'm closing this issue.  Please reopen if you have more to add to the issue.
