### ISSUE TITLE
Wheel support for linux aarch64 [arm64]

### ISSUE THREAD

**Issue by odidev** [uqfoundation/multiprocess#75]
Summary
Installing multiprocess on aarch64 via pip using command "pip3 install multiprocess" tries to build wheel from source code

Problem description
multiprocess doesn't have wheel for aarch64 on PyPI repository. So, while installing multiprocess via pip on aarch64, pip builds wheel for same resulting in it takes more time to install multiprocess. Making wheel available for aarch64 will benefit aarch64 users by minimizing multiprocess installation time.

Expected Output
Pip should be able to download multiprocess wheel from PyPI repository rather than building it from source code.

@multiprocess-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make multiprocess wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by odidev** [comment]
Manylinux2014 ensures that the wheel is built against the AArch64 v8.0 specification. All AArch64 platforms in the v8 series maintain backward compatibility with v8.0. So a binary built for v8.0 can run on any v8 platform. Enabling aarch64 wheel support will benefit arm v8 series users by reducing installation time. Can you please let me know if you have any interest in releasing aarch64 wheels?

**Comment by odidev** [comment]
@mmckerns, can you please let me know your interest here? Thanks in advance.
CC: @EvanMcKerns, @LuAPi

**Comment by mmckerns** [comment]
@odidev: in python 2, `multiprocess` has a need for platform-specific wheels... however with python 3, the wheels are platform independent as in python 3 `multiprocess` is pure python.  Can you clarify why, aside from a slightly faster one-time install, would it be beneficial for aarch64 users that an aarch64-specific binary wheel is released?  It's my understanding that the currently released python 3 wheels provide sufficient support for aarch64 users.  Am I mistaken?

**Comment by odidev** [comment]
@mmckerns, it was my system's configuration problem. Somehow pip was referring to python2.7. Now, I corrected the problem with your inputs and its working fine now. Closing the issue. Thanks for your help.

**Comment by mmckerns** [comment]
> I corrected the problem with your inputs and its working fine now.

If you have found an issue and created a patch, then please do submit the patch in a PR.
