### ISSUE TITLE
how to pass variables to function executed in parallel

### ISSUE THREAD

**Issue by vertikal-andrea** [uqfoundation/multiprocess#77]
I have written some code to parallelize the processing of some data in a Jupyter notebook.

It consists of a function taking some data as input, transforming them and writing the result in a file:
```
%%writefile my_functions.py
import pickle

def my_function(f):

    d = f*10

    with open(f"{v}.p", "wb") as f:
        pickle.dump(d, f, pickle.HIGHEST_PROTOCOL)
```
The function is called in the main:
```
from multiprocess import Pool
from my_functions import my_function
from tqdm import tqdm

values_list = [0, 1, 2, 3, 4, 5, 6]

max_pool = 5

factor=10

with Pool(max_pool) as p:
    pool_outputs = list(
        tqdm(
            p.imap(my_function,
                   values_list),
            total=len(values_list)
        )
    )    
```

How can I modify the code in order to pass some variables to my_function? For example, let's suppose I want to pass the value of a variable `v`:
```
%%writefile my_functions.py
import pickle

def my_function(f,v):

    d = f*v

    with open(f"{v}.p", "wb") as f:
        pickle.dump(d, f, pickle.HIGHEST_PROTOCOL)
```

How can I modify the call to p.imap accordingly?

**Comment by mmckerns** [comment]
Sorry for ignoring this question, apparently.  Hopefully you figured it out.
I'd answer like this...
if you need to pass multiple arguments, then use `starmap`:
```
>>> import multiprocess as mp
>>> f = lambda x,y: x*y
>>> p = mp.Pool()
>>> p.starmap(f, zip([1,2,3,4],[5,6,7,8]))
[5, 12, 21, 32]
```
...or wrap a lambda around `f` to enable `imap` to work like `starmap`: 
```
>>> g = lambda args: f(*args)
>>> res = p.imap(g, zip([1,2,3,4],[5,6,7,8]))
>>> list(res)
[5, 12, 21, 32]
```
I'm going to close this.  Please reopen if there's more to discuss.
