### ISSUE TITLE
How important it is to have C compiler to use multiprocess (and pathos) on Windows?

### ISSUE THREAD

**Issue by abrazhe** [uqfoundation/multiprocess#8]
Actually, there are several 'issues' (on windows, python2.7):
- when installing  with `pip install .` (from the repo directory), _no warning_ about missing C compiler is issued.
- when installing  with `pip install .` (and having no C compiler)  it is impossible to import `multiprocess` because it complains about missing `_multiprocess`
- when installing via `python setup.py install` it does warn about missing C compiler, but promises that most functionality will be available. `import multiprocess` still raises ImportError missing `_multiprocess`

So, if not having C compiler makes it impossible to import multiprocess, then may be it should be an error, not a warning?

What free (open) C compiler can I install on windows so multiprocess can build its extensions?

I may be doing something wrong here, so please correct me if the problem is actually very simple.

**Comment by mmckerns** [comment]
Yes, that's correct… for the `2.x` series, you need a C compiler to build the full `multiprocess` functionality.  Without it, you'll fall back to the python standard library `_multiprocessing`, and thus won't have "advanced" serialization benefits from `dill`.

**Comment by mmckerns** [comment]
This is what I have used on Windows:
```
# installed Visual Studio Community 2015 RC
# installed Python Tools 2.2 RC for Visual Studio 2015
# installed Microsoft Visual C++ Compiler for Python 2.7
# installed Miniconda 3.10.1 (64-bit) for Python 2.7
# installed Git for Windows 1.9.5-preview20150319 (including cmd tools)
>$ conda install pip
>$ conda install setuptools
>$ pip install git+https://github.com/uqfoundation/pathos.git@master
```

**Comment by mmckerns** [comment]
Hmm. If `import multiprocess` throws an error when a C compiler is missing, then issuing a build warning is probably the correct thing to do.  I did not change the behavior from what python itself does, but maybe I should.

**Comment by abrazhe** [comment]
Quickfix solution for those who (like me) don't know anything about C compilers on windows and how and which to install:

  1. Install "Microsoft Visual C++ 2008 SP1 Redistributable Package (x64)" from http://www.microsoft.com/en-us/download/confirmation.aspx?id=2092
  2. Install Microsoft Visual C++ for Python from http://aka.ms/vcpython27
  3. Build and install multiprocess

**Comment by mmckerns** [comment]
@abrazhe: Thanks for your comment.

**Comment by mmckerns** [comment]
Workaround (import `_multiprocessing` if `_multiprocess` is not found) added in: 02c1480e3e0a8d6740a2234f1f757d8d90dc7705.   This should fix most of the issues from this ticket, with the exception of the issue of `pip install .` not emitting a warning.

**Comment by mmckerns** [comment]
I should probably build wheels for `multiprocess`.  I'll open a ticket.  I'm closing this one.
