### ISSUE TITLE
KeyError: 'builtins' when invoking numpy in multiprocess

### ISSUE THREAD

**Issue by wfwzy2012** [uqfoundation/multiprocess#82]
# description
When using sum,max,min in numpy, multiprocess throw KeyError: '__builtins__'. 
It only happens with usage of data.sum() where data is a numpy array and dill.settings['recurse'] = True, while np.sum(data) works just fine.

# reproduction
```
import numpy as np
from pathos.helpers import freeze_support
from multiprocess import Pool
import dill
dill.settings['recurse'] = True  # necessary for reproduction

def f(x):
    d = np.zeros(10, dtype=np.float)
    return d.sum()  # np.sum(d) works fine

if __name__ == '__main__':
    freeze_support()
    p = Pool(4)
    result = p.map_async(f, range(1))
    print(result.get())
```
>multiprocess.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\site-packages\multiprocess\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\site-packages\multiprocess\pool.py", line 44, in mapstar
    return list(map(*args))
  File "\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*.py", line 9, in f
    return d.sum()
KeyError: '__builtins__'

# env info
os: windows10
python version: 3.6.7
multiprocess version: 0.70.12.dev0
dill version: 0.3.4.dev0

**Comment by mmckerns** [comment]
Changes to `dill` (https://github.com/uqfoundation/dill/commit/481809f4d675deb5e92797898b2c6ec5bd4b69b0,  https://github.com/uqfoundation/dill/issues/219) may fix this issue.  Can you check it?  I'm not seeing errors (on a mac) with this update.

**Comment by mmckerns** [comment]
After further testing, I believe this is resolved due to the changes noted above.  Please reopen if it's still an issue for you.
