### ISSUE TITLE
dill incompatibility

### ISSUE THREAD

**Issue by ptiwari2407** [uqfoundation/multiprocess#83]
Multiprocess has a bug where-by it's dependency is not supported for old dills-library. If possible, please fix

**Comment by mmckerns** [comment]
Can you provide more details, and be a bit more explicit? It's unclear to me as to what you are reporting.

**Comment by ptiwari2407** [comment]
![Multi-process-bug](https://user-images.githubusercontent.com/31136562/118605609-c0b5c180-b7b6-11eb-99a4-c74516a7dc8d.png)


This is not just a pycharm interpreter error. I get this error everywhere(on the terminal as well). I have used multiprocess before, I did not received error earlier. It's a fairly recent process. 
This is what I Run :
```
import multiprocess as mp
p = mp.Pool(mp.cpu_count())
```

**Comment by mmckerns** [comment]
I can't reproduce this issue.  Can you provide more details on the versions of the packages you have installed?  Also, it looks like you are on windows and using a virtual environment, is that correct?  Is it only in python 3.7?

**Comment by mmckerns** [comment]
It looks like the handling of `main` is involved in your issue.  I don't see anything do do with `dill`.  The traceback indicates either `runpy` or `multiprocess`.   Do you experience the same thing if you use an `if __name__ == '__main__'` block?  How about with `freeze_support`?  How about using `multiprocessing` instead of `multiprocess`?

**Comment by ptiwari2407** [comment]
Yes, i experience the same with `if __name__ == '__main__"` block. Yes, it does asks for freeze_support, but I can not find the resources to implement freeze support. Could you provide some directions how I can resolve this?

**Comment by mmckerns** [comment]
Try adding this to `__main__`:
```
>>> import multiprocess as mp
>>> mp.freeze_support()
```

**Comment by mmckerns** [comment]
Is this resolved? (i.e. can this be closed?)

**Comment by ptiwari2407** [comment]
Yes, The issue is resolved. Thank you very much. This is a problem for ` __main__ ` and after I put it inside `__main__` , it is resolved. This is a problem only in windows. 

Thanks. I will close the issue now :)
