### ISSUE TITLE
Python 3.5 installation fail

### ISSUE THREAD

**Issue by hasB4K** [uqfoundation/multiprocess#9]
Hi,

Since the new Python 3.5 release the setup script fail to work.
I have done the (obvious) following at the root of the repository:

$ cp -rf py3.4 py3.5
$ sudo python setup.py install

And it works perfectly.
I think it will be great that the setup script fallback to the last version supported by Multiprocess.
I have not yet experimented issue with Python 3.5 and Multiprocess, but I do not use the entire module.

Best regards,

**Comment by mmckerns** [comment]
Nice thought.  I just added support for `3.5` in 45d43608d5be4fe97680fca4817d24c5f8a882d1.  However, to have fallback support probably makes sense, I guess.  There are slight changes to each version that are different per version of python… but semi-broken is probably better than missing.  I think,
