### ISSUE TITLE
multiprocss not triggered

### ISSUE THREAD

**Issue by GZ82** [uqfoundation/multiprocess#90]
Hi here is my wrapper  function of multiprocess, basically to multiprocess a list using pool.map()
but it seems the multirpocessing never triggered, though can run it
because can not detect from $ top
and also actually slower than single thread
here is my code:

```
def multiprocessor_v1(func, ls, numCores, unlist=True, **kwargs):
      core_pool = multiprocess.Pool(processes=numCores, maxtasksperchild=1000)  # maxtasksperchild=10000
      len_obj = len(ls)
      sizeChunk = len_obj//numCores+1
      chunks = [ls[_:_+sizeChunk] for _ in range(0, len_obj, sizeChunk)]
      # multiprocessing start here
      results = core_pool.map(partial(func, **kwargs), chunks)
      core_pool.close()   
      core_pool.join()
      if unlist:
      results = [_ for sublist in results for _ in sublist] # if sublist is not None
      return results

# define a function to process
def get_bool_idx(x, y):
      return [(_ in y) for _ in x]

# run multiprocess, in which the data_array have 3 million rows
bool_idx = multiprocessor(get_bool_idx, list(data_array[:, 1]), numCores=5, unlist=True, y=targets)
```

I wonder if this is because the server I am using is heavily used by others, and there is a priority setting
any suggestions will be highly appreciated!

**Comment by mmckerns** [comment]
What do you mean, it is never triggered?  Are you saying that it's running serially?  If this is indeed the code you are testing, I would expect that `multiprocess` may be slower, and you'd better off running on a single processor.  You might want to try to use multithreading for this particular function, or multiprocess's shared memory, or a try converting to a numpy array.

Also, if you are going to call your top-level function a few times, then I think you may not want to create the Pool each time and shut it down each time -- which will slow down your code -- and you could create the pool externally, and either pass in the pool instance or the map instance.  Setting up the pool, and shutting it down will dramatically eat into your parallel processing time.

**Comment by GZ82** [comment]
> What do you mean, it is never triggered? Are you saying that it's running serially? If this is indeed the code you are testing, I would expect that `multiprocess` may be slower, and you'd better off running on a single processor. You might want to try to use multithreading for this particular function, or multiprocess's shared memory, or a try converting to a numpy array.
> 
> Also, if you are going to call your top-level function a few times, then I think you may not want to create the Pool each time and shut it down each time -- which will slow down your code -- and you could create the pool externally, and either pass in the pool instance or the map instance. Setting up the pool, and shutting it down will dramatically eat into your parallel processing time.

Hi mmckerns thanks so much for your valuable suggestions!!! I need to learn more to figure difference between threads and process will update here once I get something useful.
for "triggered", yes I meant " it's not running serially?" because I did not see much cpu usage during the run, 
and this is the code I tested
I will try your suggestion such as multiprocess's shared memory

**Comment by mmckerns** [comment]
It is definitely spawning parallel python instances... but I'd expect that it's taking longer to get the instances set up than it is to run the target function.  Try `import multiprocess.dummy as multithread`, then `multithread.Pool()`.  Or, if you want to check that your parallel cores are being used, then put a `time.sleep(1)` in your target function for testing purposes.

**Comment by mmckerns** [comment]
I'm closing this. Feel free to reopen if you feel your question wasn't answered.
